name: sgs

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - cudatoolkit=11.8
  - pytorch=2.4
  - pytorch-cuda=11.8
  - torchvision=0.19
  - numpy<2
  - click=8.1
  - hydra-core=1.3
  - kornia=0.7
  - opencv=4.10
  - pandas=2.2
  - pip=24.3
  - plyfile=1.1
  - scipy=1.14
  - screeninfo=0.8
  - tqdm=4.67

  - pip:
      - submodules/diff-gaussian-rasterization
      - submodules/simple-knn
      - imagecodecs[all]
